// Section 46: Complete Stylesheet
// Aggregated CSS output — all classes from all sections combined into a single copyable block.
// This section is a reference/export section, not a visual demo section.

import type { SectionGeneratorContext, RenderedSection } from '../../types';
import { wrapSection } from '../BaseSectionTemplate';
import { registerSection } from '../SectionRegistry';

function completeStylesheetGenerator(ctx: SectionGeneratorContext): RenderedSection {
  const { tokens } = ctx;
  const p = tokens.prefix;

  const demoHtml = `<div style="font-family: ${tokens.typography.bodyFont}; font-size: 14px; color: ${tokens.colors.gray[600]};">
    <p style="margin-bottom: 12px;">The complete stylesheet combines all CSS classes from every section above into a single file.
    Copy the full block below and include it in your project.</p>
    <div style="display: flex; gap: 16px; flex-wrap: wrap;">
      <div style="background: ${tokens.colors.primary[50]}; padding: 12px 16px; border-radius: ${tokens.radius.md}; text-align: center;">
        <div style="font-size: 24px; font-weight: 700; color: ${tokens.colors.primary[400]};">48</div>
        <div style="font-size: 12px;">Sections</div>
      </div>
      <div style="background: ${tokens.colors.gray[50]}; padding: 12px 16px; border-radius: ${tokens.radius.md}; text-align: center;">
        <div style="font-size: 24px; font-weight: 700; color: ${tokens.colors.gray[700]};">150+</div>
        <div style="font-size: 12px;">CSS Classes</div>
      </div>
      <div style="background: ${tokens.colors.gray[50]}; padding: 12px 16px; border-radius: ${tokens.radius.md}; text-align: center;">
        <div style="font-size: 24px; font-weight: 700; color: ${tokens.colors.gray[700]};">.${p}-*</div>
        <div style="font-size: 12px;">Prefix</div>
      </div>
    </div>
  </div>`;

  // Note: The actual concatenated CSS will be built by DocumentAssembler,
  // which collects CSS from all sections. Here we provide a placeholder instruction.
  const cssCode = `/*
 * ${tokens.prefix.toUpperCase()} Design System — Complete Stylesheet
 * Generated by Brand Styleguide Generator
 *
 * Usage:
 * 1. Copy this entire stylesheet into your project
 * 2. Include Google Fonts: ${tokens.typography.googleFontsUrl || 'N/A'}
 * 3. Apply classes with the .${p}- prefix
 *
 * Sections included:
 *   1. Color Palette            17. Process Steps
 *   2. Typography               18. Pricing Cards
 *   3. Section Backgrounds      19. FAQ / Accordion
 *   4. Buttons                  20. Breadcrumbs
 *   5. Cards                    21. Stats & Counters
 *   6. Images                   22. Animations
 *   7. Lists                    23. Hover Effects
 *   8. Badges & Tags            24. Responsive Utilities
 *   9. Icon Boxes               25. Page Compositions
 *  10. Forms                    26-36. Site Components
 *  11. Tables                   37. Form & Button States
 *  12. Reviews                  38. Skeleton Loading
 *  13. CTA Blocks               42. Accessibility
 *  14. Hero Sections            45. Global Settings
 *  15. Dividers
 *  16. Alerts
 *
 * Full CSS is assembled during document generation.
 * See individual sections above for per-component CSS.
 */`;

  const html = wrapSection(46, 'Complete Stylesheet', 'site-wide', {
    description: 'The complete design system CSS in a single copyable block. This aggregates all component classes from every section. Include this single file in your project for the full design system.',
    tip: 'Download the full stylesheet or copy from the code block below. Remember to also include the Google Fonts link tag in your HTML head.',
    demoHtml,
    classRefs: [],
    cssCode,
  });

  return { id: 46, anchorId: 'section-46', title: 'Complete Stylesheet', category: 'site-wide', html, classesGenerated: [] };
}

registerSection(46, completeStylesheetGenerator);
export { completeStylesheetGenerator };
