import { SiteInventoryItem, EnrichedTopic } from '../types';

const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

const getRelativePath = (url: string): string => {
    try {
        const urlObj = new URL(url);
        return urlObj.pathname + urlObj.search;
    } catch (e) {
        // If it's already relative or invalid, return as is, stripping host if it looks like one
        return url.replace(/^https?:\/\/[^/]+/, '');
    }
};

export const generateRedirectMap = (
    inventory: SiteInventoryItem[], 
    topics: EnrichedTopic[], 
    format: 'csv' | 'htaccess' | 'nginx'
) => {
    const redirects = inventory.filter(item => 
        (item.action === 'REDIRECT_301' || item.action === 'MERGE' || item.action === 'CANONICALIZE') && 
        item.mapped_topic_id
    );

    const map = redirects.map(item => {
        const targetTopic = topics.find(t => t.id === item.mapped_topic_id);
        const targetSlug = targetTopic ? targetTopic.slug : '';
        // Ensure target slug starts with /
        const cleanTarget = targetSlug.startsWith('/') ? targetSlug : `/${targetSlug}`;
        
        return {
            source: getRelativePath(item.url),
            target: cleanTarget,
            type: item.action === 'CANONICALIZE' ? 'Canonical' : '301'
        };
    });

    let content = '';
    let filename = 'redirect-map';
    let mimeType = 'text/plain';

    if (format === 'csv') {
        content = 'Source URL,Target URL,Type\n' + map.map(r => `${r.source},${r.target},${r.type}`).join('\n');
        filename += '.csv';
        mimeType = 'text/csv';
    } else if (format === 'htaccess') {
        content = '# 301 Redirects Generated by Holistic SEO Workbench\n';
        content += map.filter(r => r.type === '301').map(r => `Redirect 301 ${r.source} ${r.target}`).join('\n');
        filename += '.htaccess';
    } else if (format === 'nginx') {
        content = '# Nginx Redirects Generated by Holistic SEO Workbench\n';
        content += map.filter(r => r.type === '301').map(r => `rewrite ^${r.source}$ ${r.target} permanent;`).join('\n');
        filename += '.conf';
    }

    downloadFile(content, filename, mimeType);
};

export const generatePruneList = (inventory: SiteInventoryItem[]) => {
    const pruneList = inventory.filter(item => item.action === 'PRUNE_410');
    const content = '# URLs to be returned as 410 Gone\n' + pruneList.map(item => getRelativePath(item.url)).join('\n');
    downloadFile(content, 'prune-list.txt', 'text/plain');
};